### ISSUE TITLE
Original Dataset and other questions

### ISSUE THREAD

**Issue by ghalter** [tamedia-ddj/brennpunkt_bauernhof_public#1]
Hi, first of all I find it to be a great step towards transparency having a github, I really appreciate this! 

I just came here to toy around with the data myself, and was wondering if there is any way to get the complete dataset or if it is confidential. 

Also, I think there is a typo in 1_Kuerzungen.ipynb it should be 
`data = pd.read_pickle("files/data_mod.pkl") `
in line 47.

Finally, even if the original dataset is not available for public, I would be interested if there would have been possibility to do a more fine grained analysis of what types of cutbacks have been performed. The combination of all cutdowns feels a little to broad and isn't reflected well in the articles. Especially knowing that the whole Direktzahlungsverodnung has over 100 Pages full of rules and looking at the focus on animal mistreatment of the derived articles. 

Thanks for you answers!

**Comment by s1co** [comment]
Hi!
Thanks for your interest in our project.
The dataset is, generally, not meant for public. But if can you assure you won’t make it publicly available and inform us about any additional interesting findings, we can provide you the data.
Unfortunately, the information about cutbacks is not more fine grained. The data doesn’t document what kind of cutback it is.
If you’re still interested in the data, send us a mail at daten@tamedia.ch.
And thank you for hinting at the typo, will be fixed right away.
Cheers
